mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("polls/", include('polls.urls')),
    path('', RedirectView.as_view(url='/polls/')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup', views.signup, name='signup')
]

polls/urls.py
"""Import the path function from django."""
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    # /polls/
    path('', views.IndexView.as_view(), name='index'),
    # /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

templates/base.html
{% load static %}
<html>
<head>
    {% block head %}
  <meta charset="utf-8">
  <link rel="stylesheet" href="{% static 'polls/style.css' %}">
  <title>{% block title%}{% endblock title%}</title>
  {% endblock head %}
</head>
<body>
    <div class="polls_list">
    {% block body %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
      {% block content %} {% endblock content%}
    {% endblock body %}
    {% block button %}<a href="{% url 'polls:index' %}"><button type="button">Back to polls list</button></a> {% endblock button%}
    </div>
</body>
</html>